name: Wairua
favicon: null
layout_spectrum: 0.12378
typography_spectrum: 0.9496714188717306
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#262261'
    - '#175577'
    - '#019d96'
    - '#0c7a87'
    - '#000000'
  brandStrength: 0.42435862543061376
  lightness: 0.2362979545723647
  saturation: 0.5626145773567259
  rhythmicContrast: 0.8658153794240206
purpose: []
